### ISSUE TITLE
在 Spacemac 的 *spacemacs* buffer 调用 blink-search 抛出错误

### ISSUE THREAD

**Issue by czqhurricnae** [manateelazycat/blink-search#31]
```
(defun blink-search-init-search-dir ()
  (when (blink-search-epc-live-p blink-search-epc-process)
    (blink-search-call-async "search_init_search_dir"
                             (with-current-buffer blink-search-start-buffer
                               default-directory))))
```

在 *spacemacs* buffer `default-directory` 的值为 `~/`，如图

![image](https://user-images.githubusercontent.com/20676402/211171093-46b1d22a-64f2-4982-9951-e8bab41d5fed.png)

进而导致传递给各个 backend 的 def init_dir(self, search_dir): 的 search_dir 参数都是 `~/`？

而 https://github.com/manateelazycat/blink-search/blob/3d42bd2db1b557f5983f0f858a630f7b390bb40c/backend/search_find_file.py#L52

os.listdir 无法解析 `~/` ?

![image](https://user-images.githubusercontent.com/20676402/211171259-7fc304af-9178-4ead-88f1-f4b03a01fc56.png)

抛出错误：

```
Exception in thread Thread-43 (<lambda>):
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/c/emacs-config/default/elpa/28.2/develop/blink-search-20221228.130811/core/search.py", line 49, in <lambda>
    search_thread = threading.Thread(target=lambda: self.search_items(prefix, ticker))
  File "/Users/c/emacs-config/default/elpa/28.2/develop/blink-search-20221228.130811/core/search.py", line 54, in search_items
    candidates = self.search_match(prefix)
  File "/Users/c/emacs-config/default/elpa/28.2/develop/blink-search-20221228.130811/backend/search_find_file.py", line 52, in search_match
    return os.listdir(self.search_dir)
FileNotFoundError: [Errno 2] No such file or directory: '~/'

```

使用 `expand-file-name` 将 `~/` 转成标准路径？

```
(defun blink-search-init-search-dir ()
  (when (blink-search-epc-live-p blink-search-epc-process)
    (blink-search-call-async "search_init_search_dir"
                             (with-current-buffer blink-search-start-buffer
                               (expand-file-name default-directory)))))
```

就不会报错了。

**Comment by manateelazycat** [comment]
确实是bug, 感谢反馈， 已经修复了。
