### ISSUE TITLE
使用时报错 TypeError: expected str, bytes or os.PathLike object, not bool

### ISSUE THREAD

**Issue by heheda123123** [manateelazycat/blink-search#43]
```
ERROR:epc:TypeError('expected str, bytes or os.PathLike object, not bool')
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "c:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\epc\handler.py", line 242, in _handle
    reply = handler(uid, *args)
            ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\epc\utils.py", line 51, in new_method
    ret = method(self, *args, **kwds)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\epc\handler.py", line 265, in _handle_call
    return ['return', uid, func(*args)]
                           ^^^^^^^^^^^
  File "c:\Users\Administrator\emacs-plugin\blink-search\blink_search.py", line 494, in search
    self.search_init_search_dir(start_directory)
  File "c:\Users\Administrator\emacs-plugin\blink-search\blink_search.py", line 436, in search_init_search_dir
    getattr(backend_var, "init_dir")(start_dir)
  File "c:\Users\Administrator\emacs-plugin\blink-search\backend\search_find_file.py", line 36, in init_dir
    self.search_path = get_project_path(search_dir)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Administrator\emacs-plugin\blink-search\core\utils.py", line 109, in get_project_path
    search_path = os.path.expanduser(search_dir)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 323, in expanduser
TypeError: expected str, bytes or os.PathLike object, not bool
ERROR:epc:TypeError('expected str, bytes or os.PathLike object, not bool')
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "c:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\epc\handler.py", line 242, in _handle
    reply = handler(uid, *args)
            ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\epc\utils.py", line 51, in new_method
    ret = method(self, *args, **kwds)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\epc\handler.py", line 265, in _handle_call
    return ['return', uid, func(*args)]
                           ^^^^^^^^^^^
  File "c:\Users\Administrator\emacs-plugin\blink-search\blink_search.py", line 494, in search
    self.search_init_search_dir(start_directory)
  File "c:\Users\Administrator\emacs-plugin\blink-search\blink_search.py", line 436, in search_init_search_dir
    getattr(backend_var, "init_dir")(start_dir)
  File "c:\Users\Administrator\emacs-plugin\blink-search\backend\search_find_file.py", line 36, in init_dir
    self.search_path = get_project_path(search_dir)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Administrator\emacs-plugin\blink-search\core\utils.py", line 109, in get_project_path
    search_path = os.path.expanduser(search_dir)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 323, in expanduser
TypeError: expected str, bytes or os.PathLike object, not bool

```

**Comment by manateelazycat** [comment]
看看 https://github.com/manateelazycat/blink-search/blob/f2d9229c59f294b052d46a958f965d757aeeefea/backend/search_find_file.py#L34 这里的 search_dir 是什么内容， 可以 print 一下

**Comment by manateelazycat** [comment]
这个错误需要进一步提供详细的重现步骤。

**Comment by heheda123123** [comment]
oo，因为后面用了好多次一直没复现出来，那我先关了，下次复现出来再补充信息
